server:
  port: 8082

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: movies
          uri: lb://movie-info-service
          predicates:
            - Path=/v1/movies/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET