apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: movie-catalog-service
    jib: {}
deploy:
  kubectl:
    manifests:
      - build/classes/java/main/META-INF/dekorate/kubernetes.yml
